name: rqst-env
channels:
  - defaults
dependencies:
  - ca-certificates=2019.5.15=0
  - certifi=2019.3.9=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1c=h7b6447c_1
  - python=3.7.3=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - box2d-py==2.3.8
    - chardet==3.0.4
    - cma==2.7.0
    - cycler==0.10.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - future==0.17.1
    - gast==0.2.2
    - grpcio==1.21.1
    - gym==0.12.5
    - h5py==2.9.0
    - idna==2.8
    - ipykernel==5.1.1
    - ipython==7.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jinja2==2.10.1
    - joblib==0.13.2
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - lasagne==0.1
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.0
    - mistune==0.8.4
    - mock==3.0.5
    - mpi4py==3.0.1
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - notebook==5.7.8
    - numpy==1.16.4
    - pandocfilters==1.4.2
    - parso==0.4.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==6.0.0
    - pip==19.1.1
    - prometheus-client==0.6.0
    - prompt-toolkit==2.0.9
    - protobuf==3.8.0
    - ptyprocess==0.6.0
    - pyglet==1.3.2
    - pygments==2.4.0
    - pyparsing==2.4.0
    - pyrsistent==0.15.2
    - python-dateutil==2.8.0
    - pyyaml==5.1.1
    - pyzmq==18.0.1
    - qtconsole==4.5.0
    - requests==2.22.0
    - rllab==0.1.0
    - scikit-learn==0.21.2
    - scipy==1.1.0
    - send2trash==1.5.0
    - six==1.12.0
    - tensorboard==1.13.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - termcolor==1.1.0
    - terminado==0.8.2
    - testpath==0.4.2
    - tornado==6.0.2
    - traitlets==4.3.2
    - urllib3==1.25.3
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.15.4
    - widgetsnbextension==3.4.2
prefix: /home/sid/miniconda3/envs/rqst-env

